config/routes.rb
Collex::Application.routes.draw do

	get "/wrapper" => "home#wrapper"
  get "/login_slider" => "home#login_slider"

	get "test_js/general_dialog"

	match '/search/list_name_facet_all' => 'search#list_name_facet_all'
	post '/search/remember_resource_toggle' => 'search#remember_resource_toggle'
	match '/search/saved' => 'search#saved'
	match '/search/save_search' => 'search#save_search'
	post '/search/remove_saved_search' => 'search#remove_saved_search'
	match '/search/browse' => 'search#browse'
	match 'browse/saved/:username/:name' => 'search#saved_permalink'
	get '/search' => 'search#index'

	post '/search/auto_complete_for_q' => 'search#auto_complete_for_q'
	post '/search/auto_complete_for_search_university' => 'search#auto_complete_for_search_university'

	post '/results/add_object_to_exhibit' => 'results#add_object_to_exhibit'
	post '/results/add_tag' => 'results#add_tag'
	post '/results/bulk_add_tag' => 'results#bulk_add_tag'
	post '/results/bulk_collect' => 'results#bulk_collect'
	post '/results/bulk_uncollect' => 'results#bulk_uncollect'
	post '/results/collect' => 'results#collect'
	post '/results/edit_tag' => 'results#edit_tag'
	match '/results/redraw_result_row_for_popup_buttons' => 'results#redraw_result_row_for_popup_buttons'
	post '/results/remove_all_tags' => 'results#remove_all_tags'
	post '/results/remove_tag' => 'results#remove_tag'
	post '/results/set_annotation' => 'results#set_annotation'
	post '/results/uncollect' => 'results#uncollect'
	post '/results/resend_exhibited_objects' => 'results#resend_exhibited_objects'

	match '/help/resources' => 'help#resources'
	match '/help/sites' => 'help#sites'

	post '/communities/view_by' => 'communities#view_by'
	post '/communities/sort_by' => 'communities#sort_by'
	post '/communities/search' => 'communities#search'
	post "/communities/page" => "communities#page"

	post '/builder/add_additional_author' => 'builder#add_additional_author'
	post '/builder/change_exhibits_group' => 'builder#change_exhibits_group'
	post '/builder/change_exhibits_cluster' => 'builder#change_exhibits_cluster'
	post '/builder/change_sharing' => 'builder#change_sharing'
	post '/builder/change_img_width' => 'builder#change_img_width'
	post '/builder/change_element_type' => 'builder#change_element_type'
	get '/builder/change_page' => 'builder#change_page'
	post '/builder/edit_exhibit_overview' => 'builder#edit_exhibit_overview'
	post '/builder/edit_text' => 'builder#edit_text'
	post '/builder/edit_header' => 'builder#edit_header'
	post '/builder/edit_element' => 'builder#edit_element'
	post '/builder/edit_illustration' => 'builder#edit_illustration'
	post '/builder/find_page_containing_element' => 'builder#find_page_containing_element'
	post '/builder/get_all_collected_objects' => 'builder#get_all_collected_objects'
	post '/builder/get_alias_users' => 'builder#get_alias_users'
	post '/builder/modify_outline' => 'builder#modify_outline'
	post '/builder/modify_outline_page' => 'builder#modify_outline_page'
	post '/builder/modify_border' => 'builder#modify_border'
	post '/builder/remove_additional_author' => 'builder#remove_additional_author'
	post '/builder/remove_exhibited_object' => 'builder#remove_exhibited_object'
	post '/builder/redraw_exhibit_page' => 'builder#redraw_exhibit_page'
	post '/builder/refresh_outline' => 'builder#refresh_outline'
	post '/builder/reset_exhibit_page_from_outline' => 'builder#reset_exhibit_page_from_outline'
	post '/builder/set_exhibit_author_alias' => 'builder#set_exhibit_author_alias'
	post '/builder/publish_exhibit' => 'builder#publish_exhibit'
	post '/builder/update_fonts' => 'builder#update_fonts'
	post '/builder/update_objects_in_exhibits' => 'builder#update_objects_in_exhibits'
	post '/builder/update_title' => 'builder#update_title'
	post '/builder/verify_title' => 'builder#verify_title'
	post '/builder/change_illustration_justification'
	post '/builder/insert_illustration'
	post '/builder/edit_row_of_illustrations'
	post '/builder/import_exhibit'
	post '/builder/modify_outline_add_first_element'

	config_file = File.join(Rails.root, "config", "site.yml")
	my_collex = 'my_collex'
	plugins = {}
	if File.exists?(config_file)
		site_specific = YAML.load_file(config_file)
		my_collex = site_specific['my_collex_url']
		plugins = site_specific['plugins'] || {}
		plugins.delete_if { |key, value| value != true }
	end
	get "/#{my_collex}" => 'my_collex#index'
	get "/#{my_collex}/results" => 'my_collex#results'
	get "/#{my_collex}/get_typewright_documents" => 'my_collex#get_typewright_documents'
	post "/#{my_collex}/results" => 'my_collex#results'

	post '/my_collex/remove_profile_picture' => 'my_collex#remove_profile_picture'
	post '/my_collex/show_profile' => 'my_collex#show_profile'
	post '/my_collex/update_profile_upload' => 'my_collex#update_profile_upload'
	post '/my_collex/update_profile' => 'my_collex#update_profile'

	if plugins['typewright']
		get "typewright/edit"
		post "typewright/remove_doc"

		namespace :typewright do
			get 'documents/not_available'
			get 'documents/not_signed_in'
			post 'documents/instructions'
			post 'documents/:id/complete' => 'documents#page_complete'
			post 'documents/:id/status' => 'documents#update_status'
			post 'documents/:id/report' => 'documents#report'
      put 'documents/:id/delete_edits' => 'documents#delete_edits'
			resources :admin do
				collection do
					get 'stats'
				end
			end
			resources :documents
			resources :lines
			resources :document_users
			resources :overviews, only: [ :index, :show ] do
				collection do
					get 'retrieve_doc'
				end
			end
		end

    get "typewright" => 'typewright/documents#index'

	end

	get "/login/logout" => "login#logout"
	post "/login/verify_login" => "login#verify_login"
	post "/login/submit_signup" => "login#submit_signup"
	post "/login/recover_username" => "login#recover_username"
	post "/login/reset_password" => "login#reset_password"
	get "/login/login_controls" => "login#login_controls"

	match "/forum/view_thread" => "forum#view_thread"
	match "/forum/view_topic" => "forum#view_topic"
	match "/forum/get_nines_obj_list_with_image" => "forum#get_nines_obj_list_with_image"
	match "/forum/get_exhibit_list" => "forum#get_exhibit_list"
	match "/forum/get_nines_obj_list" => "forum#get_nines_obj_list"
	post "/forum/post_comment_to_existing_thread" => "forum#post_comment_to_existing_thread"
	match "/forum/result_count" => "forum#result_count"
	post "/forum/edit_existing_comment" => "forum#edit_existing_comment"
	post "/forum/delete_comment" => "forum#delete_comment"
	post "/forum/post_comment_to_new_thread" => "forum#post_comment_to_new_thread"
	match "/forum/get_all_topics" => "forum#get_all_topics"
	post "/forum/post_object_to_new_thread" => "forum#post_object_to_new_thread"
	post "/forum/report_comment" => "forum#report_comment"
	post '/forum/get_object_details' => 'forum#get_object_details'

	post "/classroom/facet_on_group" => "classroom#facet_on_group"
	post "/classroom/search" => "classroom#search"
	post "/classroom/sort_by" => "classroom#sort_by"
	post "/classroom/view_by" => "classroom#view_by"
	post "/classroom/page" => "classroom#page"

	post "/groups/remove_profile_picture/:id" => "groups#remove_profile_picture"
	get '/groups/stale_request' => 'groups#stale_request', :as => :stale_request
	get '/groups/accept_request' => 'groups#accept_request', :as => :accept_request
	get '/groups/decline_request' => 'groups#decline_request', :as => :decline_request
	match '/groups/decline_invitation' => 'groups#decline_invitation', :as => :decline_invitation
	match '/groups/accept_invitation' => 'groups#accept_invitation', :as => :accept_invitation
	get '/groups/acknowledge_notification' => 'groups#acknowledge_notification', :as => :acknowledge_notification
	match '/groups/create_login' => 'groups#create_login', :as => :create_login
	match 'groups/create_login_create' => 'groups#create_login_create'
	get '/groups/:group/:cluster' => 'clusters#show'
	post "/groups/limit_exhibit" => "groups#limit_exhibit"
	post "/groups/unlimit_exhibit" => "groups#unlimit_exhibit"
	post "/groups/sort_exhibits" => "groups#sort_exhibits"
	post "/groups/unpublish_exhibit" => "groups#unpublish_exhibit"
	post "/groups/group_exhibits_list" => "groups#group_exhibits_list"
	post "/groups/notifications" => "groups#notifications"
	post "/groups/edit_membership" => "groups#edit_membership"
	post "/groups/render_license" => "groups#render_license"
	post "/groups/check_url" => "groups#check_url"
	post "/groups/edit_thumbnail" => "groups#edit_thumbnail"
	post "/groups/sort_cluster" => "groups#sort_cluster"
	post "/groups/leave_group" => "groups#leave_group"
	post "/groups/request_join" => "groups#request_join"
	post "/groups/verify_group_title" => "groups#verify_group_title"
	post '/groups/get_all_groups' => 'groups#get_all_groups'
	post '/groups/accept_as_peer_reviewed' => 'groups#accept_as_peer_reviewed'
	post '/groups/reject_as_peer_reviewed' => 'groups#reject_as_peer_reviewed'
	post '/groups/pending_requests' => 'groups#pending_requests'

	post "/clusters/remove_profile_picture" => "clusters#remove_profile_picture"
	post "/clusters/move_exhibit" => "clusters#move_exhibit"
	post "/clusters/edit_thumbnail" => "clusters#edit_thumbnail"
	post "/clusters/check_url" => "clusters#check_url"

	post "/admin/default/refresh_cached_objects" => "admin/default#refresh_cached_objects"
	get "/admin/facet_tree/index" => "admin/facet_tree#index"
	get "/admin/features/index" => "admin/features#index"
	get "/admin/user_roles/index" => "admin/user_roles#index"
	get "/admin/discussion_topics/index" => "admin/discussion_topics#index"
	get "/admin/default/forum_pending_reports" => "admin/default#forum_pending_reports"
	get "/admin/default/stats" => "admin/default#stats"
	get "/admin/default/groups" => "admin/default#groups"
	get "/admin/default/user_content" => "admin/default#user_content"
	get "/admin/default/use_test_index" => "admin/default#use_test_index"

app/controllers/exhibit_elements_controller.rb
##########################################################################
# Copyright 2009 Applied Research in Patacriticism and the University of Virginia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

class ExhibitElementsController < Admin::BaseController
  # GET /exhibit_elements
  # GET /exhibit_elements.xml
  def index
    @exhibit_elements = ExhibitElement.all()

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @exhibit_elements }
    end
  end

  # GET /exhibit_elements/1/edit
  def edit
    @exhibit_element = ExhibitElement.find(params[:id])
  end

  # PUT /exhibit_elements/1
  # PUT /exhibit_elements/1.xml
  def update
    @exhibit_element = ExhibitElement.find(params[:id])

    respond_to do |format|
      if @exhibit_element.update_attributes(params[:exhibit_element])
        flash[:notice] = 'ExhibitElement was successfully updated.'
        format.html { redirect_to(@exhibit_element) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @exhibit_element.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibit_elements/1
  # DELETE /exhibit_elements/1.xml
  def destroy
    @exhibit_element = ExhibitElement.find(params[:id])
    @exhibit_element.destroy

    respond_to do |format|
      format.html { redirect_to(exhibit_elements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/exhibit_elements_helper.rb
##########################################################################
# Copyright 2009 Applied Research in Patacriticism and the University of Virginia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

module ExhibitElementsHelper
  def get_exhibit_id(exhibit)
    return exhibit.visible_url && exhibit.visible_url.length > 0 ? exhibit.visible_url : exhibit.id
  end
  
  def get_exhibit_url(exhibit)
    return "/exhibits/#{get_exhibit_id(exhibit)}"
  end
  
  def get_exhibit_link(exhibit)
    return raw("<a class='nav_link' href='#{get_exhibit_url(exhibit)}'>#{exhibit.title}</a>")
  end

	def get_cluster_link(cluster_id)
		return nil if cluster_id == nil
		cluster = Cluster.find_by_id(cluster_id)
		return nil if cluster == nil
		return link_to(cluster.get_truncated_name(), cluster.get_visible_url(), { :class => 'nav_link' })
	end

  def get_exhibits_username(exhibit)
    user = exhibit.get_apparent_author()
    return user.fullname
  end
  
  def get_exhibits_username_list(exhibit, is_edit_mode)
    users = exhibit.get_authors()
	names = ""
	users.each {|user|
		del_link = ''
		if names.length > 0
			if user.id == users.last.id
				names += ' and '
			else
				names += ', '
			end
			del_link = link_to_function("[X]", "serverAction({action: { actions: '/builder/remove_additional_author', els: 'exhibit_page', params: { exhibit_id: #{exhibit.id}, user_id: #{user.id}} }, progress: { waitMessage: 'Removing Author...' })", :class => 'nav_link')
		end
		names += user.fullname
		if names.length > 0 && is_edit_mode
			names += del_link
		end
	}
    return raw(names)
  end

	def get_exhibits_user_institution(exhibit)
		users = exhibit.get_authors()
		return "" if users.length > 1
		user = exhibit.get_apparent_author()
		return user.institution ? user.institution : ''
	end
  
  def get_exhibit_user_link(exhibit)
    users = exhibit.get_authors()
	names = ""
	users.each {|user|
		if names.length > 0
			if user.id == users.last.id
				names += ' and '
			else
				names += ', '
			end
		end
		names += get_user_link(user)
	}
    return raw(names)
  end

	def draw_footnote(footnote_id, parent_id, is_edit_mode)
		if footnote_id
			click = is_edit_mode ? "" : "var footnote = $(this).next(); new MessageBoxDlg(\"Footnote\", footnote.innerHTML); "
			html = "<a href='#' onclick='#{click}return false;' class='superscript'>@</a>\n"
			html += "<span id='footnote_for_#{parent_id}' class='hidden'>#{is_edit_mode ? ExhibitFootnote.find(footnote_id).footnote : decode_exhibit_links(ExhibitFootnote.find(footnote_id).footnote)} </span>\n"
			return raw(html)
		end
		return ""
	end
end

app/views/exhibit_elements/edit.html.erb
<% #
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0

    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<h1>Editing exhibit_element</h1>

<%= error_messages_for :exhibit_element %>

<%= form_for(@exhibit_element) do |f| %>
  <p>
    <b>Exhibit page</b><br />
    <%= f.text_field :exhibit_page_id %>
  </p>

  <p>
    <b>Position</b><br />
    <%= f.text_field :position %>
  </p>

  <p>
    <b>Border type enum</b><br />
    <%= f.text_field :border_type_enum %>
  </p>

  <p>
    <b>Exhibit element layout type</b><br />
    <%= f.text_field :exhibit_element_layout_type %>
  </p>

  <p>
    <b>Element test</b><br />
    <%= f.text_area :element_text %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @exhibit_element, :class => 'nav_link' %> |
<%= link_to 'Back', exhibit_elements_path, :class => 'nav_link' %>

app/views/exhibit_elements/index.html.erb
<% #
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0

    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<h1>All Exhibit Elements</h1>

<% records = [] -%>
<% for exhibit_element in @exhibit_elements
	record = {}
	exhibit = nil
	page = ExhibitPage.find_by_id(exhibit_element.exhibit_page_id)
	if page != nil
		exhibit = Exhibit.find_by_id(page.exhibit_id)
	end

	record[:exhibit_element] = exhibit_element
	record[:exhibit_element_id] = exhibit_element.id
	if exhibit == nil
		record[:exhibit] = 'Orphan'
	else
		record[:exhibit] = "#{exhibit.id} #{exhibit.title}"
	end

	if page == nil
		record[:page] = 'Orphan'
		record[:page_pos] = -1
	else
		record[:page] = "#{page.id} (pos: #{page.position})"
		record[:page_pos] = page.position
	end

    record[:position] = exhibit_element.position
    record[:layout_type] = exhibit_element.exhibit_element_layout_type
    record[:thumbnail] = element_text_thumbnail(exhibit_element.element_text)
	record[:illustration_list] = ""
	exhibit_element.exhibit_illustrations.each { |ill| record[:illustration_list] += "#{ill['id']}," }
	
	record[:new_page] = exhibit_element.exhibit_page_id
	record[:border] = exhibit_element.border_type_enum
	records.insert(-1, record)
end -%>
<% records = records.sort { |x,y|
	if x[:exhibit] < y[:exhibit]
		-1
	elsif x[:exhibit] > y[:exhibit]
		1
	elsif x[:page_pos] < y[:page_pos]
		-1
	elsif x[:page_pos] > y[:page_pos]
		1
	elsif x[:position] < y[:position]
		-1
	elsif x[:position] > y[:position]
		1
	else
		0
	end
}
-%>

<table border='1px solid black' cellspacing=0>
  <tr>
  	<th>ID</th>
	<th>Exhibit</th>
	<th>page</th>
    <th>Position</th>
    <th>Layout type</th>
    <th>Element text</th>
	<th>Illustration list</th>
	<th>border</th>
  </tr>

<% for record in records %>
  <tr>
    <td><%= record[:exhibit_element_id] %></td>
    <td><%= record[:exhibit] %></td>
    <td><%= record[:new_page] %>/<%= record[:page] %></td>
    <td><%= record[:position] %></td>
    <td><%= record[:layout_type] %></td>
    <td><%= record[:thumbnail] %></td>
    <td><%= record[:illustration_list].each { |ill| "#{ill['id']}," } %></td>
    <td><%= record[:border] %></td>
    <td><%= link_to 'Edit', edit_exhibit_element_path(record[:exhibit_element]), :class => 'nav_link' %></td>
    <td><%= link_to 'Destroy', record[:exhibit_element], :confirm => 'Are you sure?', :method => :delete, :class => 'modify_link' %></td>
  </tr>
<% end %>
</table>

<h1>Exhibits # pages:</h1>
<% exhibits = Exhibit.all()
	for exhibit in exhibits -%>
		<%= "#{exhibit.id}: #{exhibit.exhibit_pages.length}" %>
		<%= link_to 'Destroy', exhibit, :confirm => 'Are you sure?', :method => :delete, :class => 'modify_link' %>
		<br />
<%end -%>

<h1>Pages # elements:</h1>
<% pages = ExhibitPage.all()
	for page in pages -%>
		<%= "#{page.id}: #{page.exhibit_elements.length}"  %>
		<%= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete, :class => 'modify_link' %>
		<br />
<%end -%>

<h1>Illustrations belong to element:</h1>
<% illustrations = ExhibitIllustration.all()
	for illustration in illustrations -%>
		<%= "#{illustration.id} -&gt; #{illustration.exhibit_element_id}"  %>
		<%= link_to 'Destroy', illustration, :confirm => 'Are you sure?', :method => :delete, :class => 'modify_link' %>
		<br />
<%end -%>

<br />

<%= link_to 'New exhibit_element', new_exhibit_element_path, :class => 'nav_link' %>
<br />

<!--
<table border='1px solid black' cellspacing=0>
  <tr>
  	<th>ID</th>
	<th>User</th>
	<th>Method</th>
    <th>URI</th>
    <th>Params</th>
    <th>Referer</th>
    <th>Time</th>
  </tr>

<%# logs = Log.find(:all, :order => 'updated_at DESC', :limit => 700 ) -%>
<%# logs = logs.sort { |a,b|
	if a.user == b.user
		b.updated_at <=> a.updated_at
	else
		au = a.user ? a.user : ''
		bu = b.user ? b.user : ''
		bu <=> au
	end
} -%>
<%# for log in logs %>
  <tr>
    <td><%#= log.id %></td>
    <td><%#= log.user %></td>
    <td><%#= log.request_method %></td>
    <td><%#= log.request_uri %></td>
    <td><%#= log.params %></td>
    <td><%#= log.http_referer %></td>
    <td><%#= log.updated_at %></td>
  </tr>
<%# end %>
</table>
-->