config/routes.rb
Collex::Application.routes.draw do

	get "/wrapper" => "home#wrapper"
  get "/login_slider" => "home#login_slider"

	get "test_js/general_dialog"

	match '/search/list_name_facet_all' => 'search#list_name_facet_all'
	post '/search/remember_resource_toggle' => 'search#remember_resource_toggle'
	match '/search/saved' => 'search#saved'
	match '/search/save_search' => 'search#save_search'
	post '/search/remove_saved_search' => 'search#remove_saved_search'
	match '/search/browse' => 'search#browse'
	match 'browse/saved/:username/:name' => 'search#saved_permalink'
	get '/search' => 'search#index'

	post '/search/auto_complete_for_q' => 'search#auto_complete_for_q'
	post '/search/auto_complete_for_search_university' => 'search#auto_complete_for_search_university'

	post '/results/add_object_to_exhibit' => 'results#add_object_to_exhibit'
	post '/results/add_tag' => 'results#add_tag'
	post '/results/bulk_add_tag' => 'results#bulk_add_tag'
	post '/results/bulk_collect' => 'results#bulk_collect'
	post '/results/bulk_uncollect' => 'results#bulk_uncollect'
	post '/results/collect' => 'results#collect'
	post '/results/edit_tag' => 'results#edit_tag'
	match '/results/redraw_result_row_for_popup_buttons' => 'results#redraw_result_row_for_popup_buttons'
	post '/results/remove_all_tags' => 'results#remove_all_tags'
	post '/results/remove_tag' => 'results#remove_tag'
	post '/results/set_annotation' => 'results#set_annotation'
	post '/results/uncollect' => 'results#uncollect'
	post '/results/resend_exhibited_objects' => 'results#resend_exhibited_objects'

	match '/help/resources' => 'help#resources'
	match '/help/sites' => 'help#sites'

	post '/communities/view_by' => 'communities#view_by'
	post '/communities/sort_by' => 'communities#sort_by'
	post '/communities/search' => 'communities#search'
	post "/communities/page" => "communities#page"

	post '/builder/add_additional_author' => 'builder#add_additional_author'
	post '/builder/change_exhibits_group' => 'builder#change_exhibits_group'
	post '/builder/change_exhibits_cluster' => 'builder#change_exhibits_cluster'
	post '/builder/change_sharing' => 'builder#change_sharing'
	post '/builder/change_img_width' => 'builder#change_img_width'
	post '/builder/change_element_type' => 'builder#change_element_type'
	get '/builder/change_page' => 'builder#change_page'
	post '/builder/edit_exhibit_overview' => 'builder#edit_exhibit_overview'
	post '/builder/edit_text' => 'builder#edit_text'
	post '/builder/edit_header' => 'builder#edit_header'
	post '/builder/edit_element' => 'builder#edit_element'
	post '/builder/edit_illustration' => 'builder#edit_illustration'
	post '/builder/find_page_containing_element' => 'builder#find_page_containing_element'
	post '/builder/get_all_collected_objects' => 'builder#get_all_collected_objects'
	post '/builder/get_alias_users' => 'builder#get_alias_users'
	post '/builder/modify_outline' => 'builder#modify_outline'
	post '/builder/modify_outline_page' => 'builder#modify_outline_page'
	post '/builder/modify_border' => 'builder#modify_border'
	post '/builder/remove_additional_author' => 'builder#remove_additional_author'
	post '/builder/remove_exhibited_object' => 'builder#remove_exhibited_object'
	post '/builder/redraw_exhibit_page' => 'builder#redraw_exhibit_page'
	post '/builder/refresh_outline' => 'builder#refresh_outline'
	post '/builder/reset_exhibit_page_from_outline' => 'builder#reset_exhibit_page_from_outline'
	post '/builder/set_exhibit_author_alias' => 'builder#set_exhibit_author_alias'
	post '/builder/publish_exhibit' => 'builder#publish_exhibit'
	post '/builder/update_fonts' => 'builder#update_fonts'
	post '/builder/update_objects_in_exhibits' => 'builder#update_objects_in_exhibits'
	post '/builder/update_title' => 'builder#update_title'
	post '/builder/verify_title' => 'builder#verify_title'
	post '/builder/change_illustration_justification'
	post '/builder/insert_illustration'
	post '/builder/edit_row_of_illustrations'
	post '/builder/import_exhibit'
	post '/builder/modify_outline_add_first_element'

	config_file = File.join(Rails.root, "config", "site.yml")
	my_collex = 'my_collex'
	plugins = {}
	if File.exists?(config_file)
		site_specific = YAML.load_file(config_file)
		my_collex = site_specific['my_collex_url']
		plugins = site_specific['plugins'] || {}
		plugins.delete_if { |key, value| value != true }
	end
	get "/#{my_collex}" => 'my_collex#index'
	get "/#{my_collex}/results" => 'my_collex#results'
	get "/#{my_collex}/get_typewright_documents" => 'my_collex#get_typewright_documents'
	post "/#{my_collex}/results" => 'my_collex#results'

	post '/my_collex/remove_profile_picture' => 'my_collex#remove_profile_picture'
	post '/my_collex/show_profile' => 'my_collex#show_profile'
	post '/my_collex/update_profile_upload' => 'my_collex#update_profile_upload'
	post '/my_collex/update_profile' => 'my_collex#update_profile'

	if plugins['typewright']
		get "typewright/edit"
		post "typewright/remove_doc"

		namespace :typewright do
			get 'documents/not_available'
			get 'documents/not_signed_in'
			post 'documents/instructions'
			post 'documents/:id/complete' => 'documents#page_complete'
			post 'documents/:id/status' => 'documents#update_status'
			post 'documents/:id/report' => 'documents#report'
      put 'documents/:id/delete_edits' => 'documents#delete_edits'
			resources :admin do
				collection do
					get 'stats'
				end
			end
			resources :documents
			resources :lines
			resources :document_users
			resources :overviews, only: [ :index, :show ] do
				collection do
					get 'retrieve_doc'
				end
			end
		end

    get "typewright" => 'typewright/documents#index'

	end

	get "/login/logout" => "login#logout"
	post "/login/verify_login" => "login#verify_login"
	post "/login/submit_signup" => "login#submit_signup"
	post "/login/recover_username" => "login#recover_username"
	post "/login/reset_password" => "login#reset_password"
	get "/login/login_controls" => "login#login_controls"

	match "/forum/view_thread" => "forum#view_thread"
	match "/forum/view_topic" => "forum#view_topic"
	match "/forum/get_nines_obj_list_with_image" => "forum#get_nines_obj_list_with_image"
	match "/forum/get_exhibit_list" => "forum#get_exhibit_list"
	match "/forum/get_nines_obj_list" => "forum#get_nines_obj_list"
	post "/forum/post_comment_to_existing_thread" => "forum#post_comment_to_existing_thread"
	match "/forum/result_count" => "forum#result_count"
	post "/forum/edit_existing_comment" => "forum#edit_existing_comment"
	post "/forum/delete_comment" => "forum#delete_comment"
	post "/forum/post_comment_to_new_thread" => "forum#post_comment_to_new_thread"
	match "/forum/get_all_topics" => "forum#get_all_topics"
	post "/forum/post_object_to_new_thread" => "forum#post_object_to_new_thread"
	post "/forum/report_comment" => "forum#report_comment"
	post '/forum/get_object_details' => 'forum#get_object_details'

	post "/classroom/facet_on_group" => "classroom#facet_on_group"
	post "/classroom/search" => "classroom#search"
	post "/classroom/sort_by" => "classroom#sort_by"
	post "/classroom/view_by" => "classroom#view_by"
	post "/classroom/page" => "classroom#page"

	post "/groups/remove_profile_picture/:id" => "groups#remove_profile_picture"
	get '/groups/stale_request' => 'groups#stale_request', :as => :stale_request
	get '/groups/accept_request' => 'groups#accept_request', :as => :accept_request
	get '/groups/decline_request' => 'groups#decline_request', :as => :decline_request
	match '/groups/decline_invitation' => 'groups#decline_invitation', :as => :decline_invitation
	match '/groups/accept_invitation' => 'groups#accept_invitation', :as => :accept_invitation
	get '/groups/acknowledge_notification' => 'groups#acknowledge_notification', :as => :acknowledge_notification
	match '/groups/create_login' => 'groups#create_login', :as => :create_login
	match 'groups/create_login_create' => 'groups#create_login_create'
	get '/groups/:group/:cluster' => 'clusters#show'
	post "/groups/limit_exhibit" => "groups#limit_exhibit"
	post "/groups/unlimit_exhibit" => "groups#unlimit_exhibit"
	post "/groups/sort_exhibits" => "groups#sort_exhibits"
	post "/groups/unpublish_exhibit" => "groups#unpublish_exhibit"
	post "/groups/group_exhibits_list" => "groups#group_exhibits_list"
	post "/groups/notifications" => "groups#notifications"
	post "/groups/edit_membership" => "groups#edit_membership"
	post "/groups/render_license" => "groups#render_license"
	post "/groups/check_url" => "groups#check_url"
	post "/groups/edit_thumbnail" => "groups#edit_thumbnail"
	post "/groups/sort_cluster" => "groups#sort_cluster"
	post "/groups/leave_group" => "groups#leave_group"
	post "/groups/request_join" => "groups#request_join"
	post "/groups/verify_group_title" => "groups#verify_group_title"
	post '/groups/get_all_groups' => 'groups#get_all_groups'
	post '/groups/accept_as_peer_reviewed' => 'groups#accept_as_peer_reviewed'
	post '/groups/reject_as_peer_reviewed' => 'groups#reject_as_peer_reviewed'
	post '/groups/pending_requests' => 'groups#pending_requests'

	post "/clusters/remove_profile_picture" => "clusters#remove_profile_picture"
	post "/clusters/move_exhibit" => "clusters#move_exhibit"
	post "/clusters/edit_thumbnail" => "clusters#edit_thumbnail"
	post "/clusters/check_url" => "clusters#check_url"

	post "/admin/default/refresh_cached_objects" => "admin/default#refresh_cached_objects"
	get "/admin/facet_tree/index" => "admin/facet_tree#index"
	get "/admin/features/index" => "admin/features#index"
	get "/admin/user_roles/index" => "admin/user_roles#index"
	get "/admin/discussion_topics/index" => "admin/discussion_topics#index"
	get "/admin/default/forum_pending_reports" => "admin/default#forum_pending_reports"
	get "/admin/default/stats" => "admin/default#stats"
	get "/admin/default/groups" => "admin/default#groups"
	get "/admin/default/user_content" => "admin/default#user_content"
	get "/admin/default/use_test_index" => "admin/default#use_test_index"

app/controllers/home_controller.rb
##########################################################################
# Copyright 2009 Applied Research in Patacriticism and the University of Virginia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

class HomeController < ApplicationController

  before_filter :init_view_options
  
  def init_view_options
    @site_section = :home
    return true
  end
  
  def redirect_to_index
    redirect_to :controller => 'home', :action => 'index'
  end
  
 def redirect_to_tag_cloud_update
    redirect_to  '/tagCloudUpdate.html'
  end

  def index

    @discussions = DiscussionTopic.get_most_popular(5)

    if Setup.site_name() == '18thConnect'
      @featured_news = true
    end
      features = FeaturedObject.where({disabled: '0'})
      if features.length > 0
        features = features.sort_by {rand}
        @feature = features[0]
      end

    #@tags = CachedResource.get_most_popular_tags(40)
    @tags = CachedResource.get_most_recent_tags(40)

      # carousel
    @carousel = Catalog.factory_create(false).get_carousel()
    @carousel = @carousel.sort_by {rand}
	
#    facets = FacetCategory.find_all_by_carousel_include(1)
#		facets = facets.sort_by {rand}
#    @carousel = []
#    for facet in facets
#      title = facet[:value]
#      url = facet[:carousel_url]
#      if facet[:type] == 'FacetValue'
#        site = Site.find_by_code(title)
#		if site
#			title = site.description
#			url = site.url
#		else
#			title = "ERR: site not found:#{title}"
#		end
#      end
#      @carousel.push({ :title => title, :description => facet[:carousel_description], :url => url, :image => facet.image_id ? "/#{facet.image.photo.url}" : '' })
#	end
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def get_footer_data
    render :partial => 'footer_data'
  end
  
  def news
    @site_section = :news
#		render :template => '/about/news'
  end

  def atom
    # This redirects the old atom feeds
     render :text => <<-CLOSE
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
 
 <title>nines.org</title>
 <subtitle>Nineteenth Century Studies Online.</subtitle>
 <link href="http://nines.org" rel="self"/>
  <id>urn:uuid:60a0000-d399-11d9-b91C-0003939e0af6</id>
 
 <entry>
   <title>NINES has been reworked!</title>
   <link href="http://nines.org"/>
   <id>urn:uuid:1005c695-cfb8-4ebb-aaaa-80da344efa6a</id>
   <summary>Click http://nines.org to see the new NINES interface.</summary>
 </entry>
 
</feed>
     CLOSE
  end
  
	def wrapper
		if params[:style] == 'post'
			@current_page = "News"
			@site_section = :news
		else
			@current_page = "About"
			@site_section = :about
		end
		render :partial => "/layouts/wrapper"
  end

  def login_slider
    render :partial => '/common/login_slider', :locals => { :current_page => @current_page }
  end
end

app/helpers/home_helper.rb
##########################################################################
# Copyright 2009 Applied Research in Patacriticism and the University of Virginia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################

module HomeHelper
end

app/views/home/_featured_exhibit.html.erb
<% # 
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
  
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<%# featured_exhibit param: none -%>
<div id="exhibit_container">
	<div id="exhibit_left"></div>
	<div id="exhibit_right"></div>
	<div id="exhibit_text">
		<p><a href="/exhibits/Lettere_A_Colori" class="nav_link"><span class="exhibit_title">Lettere A Colori: Descrizioni di dipinti nella corrispondenza di Dante Gabriel Rossetti</span></a> <br />by Federica Mazzara</p>
		<p>In many letters sent to his parents and friends, Dante Gabriel Rossetti (1828-1882) included verbal translations, or descriptions of paintings - properly known as <i>ekphraseis</i> - as a way to explore and express more fully his own thoughts on art and aesthetics. A study of this correspondence allows a glimpse into not only the creative process, but also the most deeply held and intimate fantasies of an artist known for his complex inner life. (<i>A note to readers: essay is in Italian.</i>)</p>
		<a href="/exhibits/Lettere_A_Colori" class="nav_link">View Exhibit</a></p></div>
	<div class="clear_both"></div>
</div>

app/views/home/_featured_news.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2011 Applied Research in Patacriticism and the University of Virginia
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
# ----------------------------------------------------------------------------
%>
<%# featured_news -%>
<div class="feature_news">
    <%= image_tag "18th/voyeur.png", { class: "voyeur_icon", alt: "Voyeur Icon" } %>
The roughly 2,000 texts released by Gale Cengage Learning and the Text Creation Partnership (<%= link_to "see the News tab", '/news/', { :class => 'nav_link' } %>)
	are <%= link_to "available for full-text searching here", '/search/saved?user=paul&name=ecco_full_text', { :class => 'nav_link' } %>.
18thConnect will soon offer access here to Voyeur: <%= link_to "Reveal Your Texts", 'http://hermeneuti.ca/voyeur', { :class => 'ext_link', :target => '_blank' } %>, a window
	that allows using TaPOR tools to analyze these texts.  If you would like to try that now, you may see any of the following texts in Voyeur:
<ul>
<li><%= link_to "Susanna Centlivre, The Artifice, a comedy (1723)", "http://voyeurtools.org/?corpus=K032308.xml&archive=http://18thConnect.org/images/18th/centlivreXML.xml&stopList=stop.en.taporware.txt&xmlAuthorXpath=//author&xmlTitleXpath=//label&xmlContentXpath=//plainText", { :class => 'ext_link', :target => '_blank' } %></li>
<li><%= link_to "Daniel Defoe, The Farther Adventures of Robinson Crusoe (1719)", "http://voyeurtools.org/?corpus=K018256.xml&archive=http://18thConnect.org/images/18th/defoeXML.xml&stopList=stop.en.taporware.txt&xmlAuthorXpath=//author&xmlTitleXpath=//label&xmlContentXpath=//plainText", { :class => 'ext_link', :target => '_blank' } %></li>
<li><%= link_to "Ottobah Cugoano, On the Evil and Wicked Traffic of Slavery (1787)", "http://voyeurtools.org/?corpus=K046227.xml&archive=http://18thConnect.org/images/18th/cugoanoXML.xml&stopList=stop.en.taporware.txt&xmlAuthorXpath=//author&xmlTitleXpath=//label&xmlContentXpath=//plainText", { :class => 'ext_link', :target => '_blank' } %></li>
<li><%= link_to "Adam Smith, The Theory of Moral Sentiments (1759)", "http://voyeurtools.org/?corpus=K111361.xml&archive=http://18thConnect.org/images/18th/smithXML.xml&stopList=stop.en.taporware.txt&xmlAuthorXpath=//author&xmlTitleXpath=//label&xmlContentXpath=//plainText", { :class => 'ext_link', :target => '_blank' } %></li>
</ul>
Send ideas or request texts: <a class="nav_link nospam" href="laura.mandell gmail com">Contact us</a>
</div>

<%#= link_to "Susanna Centlivre, The Artifice, a comedy (1723)", "http://voyeurtools.org/?corpus=K032308.xml&archive=http://18thConnect.org/images/18th/centlivreXML.xml&stopList=stop.en.taporware.txt", { :class => 'ext_link', :target => '_blank' } %>
<%#= link_to "Daniel Defoe, The Farther Adventures of Robinson Crusoe (1719)", "http://voyeurtools.org/?corpus=K018256.xml&archive=http://18thConnect.org/images/18th/defoeXML.xml&stopList=stop.en.taporware.txt", { :class => 'ext_link', :target => '_blank' } %>
<%#= link_to "Ottobah Cugoano, On the Evil and Wicked Traffic of Slavery (1787)", "http://voyeurtools.org/?corpus=K046227.xml&archive=http://18thConnect.org/images/18th/cugoanaXML.xml&stopList=stop.en.taporware.txt", { :class => 'ext_link', :target => '_blank' } %>
<%#= link_to "Adam Smith, The Theory of Moral Sentiments (1759)", "http://voyeurtools.org/?corpus=K111361.xml&archive=http://18thConnect.org/images/18th/smithXML.xml&stopList=stop.en.taporware.txt", { :class => 'ext_link', :target => '_blank' } %>

app/views/home/_featured_resource.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2010 Applied Research in Patacriticism and the University of Virginia
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
# ----------------------------------------------------------------------------
%>
<%# featured_resource param: ActiveRecord feature -%>
<table class="feature_resource"><tr>
<td class="feature_image">
   <% if feature.image.nil? %>
      <%= image_tag "#{SKIN}/lg_site_image.gif" %>
   <% else %>
	  <img src="/<%= feature.image.photo.url(:feature) %>" alt="Featured Resource" />
	<% end %>
</td>
<td class="feature_text">
	<div class="feature_text_header"><%= link_to feature.title, feature.object_url, { :class => 'nines_link' } %></div>
	<div class="search_result_data_container">
		 <div class="feature_text_data">
			<div class="feature_text_data_label">Date:</div>
			<div class="feature_text_data_value"><%= feature.date %></div>
			<div class="feature_text_data_label">Site:</div>
			<div class="feature_text_data_value"><%= link_to feature.site, feature.site_url, { :class => 'ext_link' } %></div>
			<div class="feature_text_saved_search">Click to browse more objects like <%= link_to feature.title, feature.saved_search_url, { :class => 'nav_link' } %></div>
		</div>
	</div>
</td>
</tr></table>

app/views/home/_footer_data.html.erb
<% # 
    # ------------------------------------------------------------------------
    # Copyright 2009 Applied Research in Patacriticism and the University of Virginia
    #
    # Licensed under the Apache License, Version 2.0 (the "License");
    # you may not use this file except in compliance with the License.
    # You may obtain a copy of the License at
    #
    #    http://www.apache.org/licenses/LICENSE-2.0
  
    # Unless required by applicable law or agreed to in writing, software
    # distributed under the License is distributed on an "AS IS" BASIS,
    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    # See the License for the specific language governing permissions and
    # limitations under the License.
    # ---------------------------------------------------------------------------- -%>
<%= raw({ :num_docs => number_with_delimiter(session[:num_docs]), :num_sites => number_with_delimiter(session[:num_sites]), :collex_version => Branding.version() }.to_json()) -%>

app/views/home/_popular_discussions.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2009 Applied Research in Patacriticism and the University of Virginia
# 
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
# 
#         http://www.apache.org/licenses/LICENSE-2.0
# 
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
# ----------------------------------------------------------------------------
%>
<%# popular_discussions param: array discussions, bool show_more -%>
<ul>
	<% if discussions -%>
	<% discussions.each {|discussion| -%>
	<li><%= link_to(discussion[:title], "/forum/view_thread?thread=#{discussion[:id]}", { :class => 'nav_link' }) %></li>
	<% } -%>
	<% if show_more -%>
	<li><%= link_to("MORE", forum_path, { :class => 'nav_link' }) %></li>
	<% end -%>
	<% end -%>
</ul>

app/views/home/_popular_tags.html.erb
<%#
# ------------------------------------------------------------------------
#     Copyright 2009 Applied Research in Patacriticism and the University of Virginia
# 
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
# 
#         http://www.apache.org/licenses/LICENSE-2.0
# 
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
# ----------------------------------------------------------------------------
%>
<%# popular_tags params: array tags -%>
<% tag_links = [] -%>
<%
   if tags
     tags.each {|tag|
       tag_links.push(
               #link_to(
               #        format_tag_for_output(tag[0]),
               #        "/tag/results?tag=#{tag[0]}&view=tag",
               #        {
               #                :title => pluralize(tag[1], 'object'),
               #                :class => tag[2] ? 'nav_link tag_lvl1' : 'nav_link'
               #        }
               link_to_function(
                       format_tag_for_output(tag[0]),
                       "serverAction({action: { actions: '/tag/results?tag=#{tag[0]}&view=tag', params: {}}, progress: { waitMessage: 'Searching...' }, searching: true})",
                       {
                               :title => pluralize(tag[1], 'object'),
                               :class => tag[2] ? 'nav_link tag_lvl1' : 'nav_link'
                       }

               )
       )
     }
   end
     -%>
<%= raw(tag_links.join(" &bull; ")) %>